import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  bottomBar: {
    height: 129,
    paddingTop: 10,
    paddingBottom: 7,
    marginBottom: 20,
    marginHorizontal: 16,
    backgroundColor: '#FAFAFA',
    borderTopWidth: 0,
    position: 'relative',
  },
  miniPlayerWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    paddingLeft: 7,
    paddingRight: 5,
    paddingTop: 10,
  },
  miniPlayerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  miniPlayerLeftCol: {
    alignItems: 'center',
  },
  miniControlButton: {
    width: 32.25,
    height: 32.225,
    borderRadius: 16.125,
    backgroundColor: '#2FA2FE',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -24.63,
  },
  pauseIconWrap: {
    flexDirection: 'row',
    gap: 3,
  },
  pauseBar: {
    width: 2,
    height: 12,
    borderRadius: 1,
    backgroundColor: '#FFFFFF',
  },
  playIcon: {
    width: 0,
    height: 0,
    borderTopWidth: 6,
    borderBottomWidth: 6,
    borderLeftWidth: 10,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#FFFFFF',
    marginLeft: 2,
  },
  miniTimeLabel: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '400',
    color: '#000000',
  },
  miniProgressCol: {
    flex: 1,
    alignItems: 'flex-start',
    marginLeft: 10.37,
    marginRight: 16,
    marginTop: 0,
  },
  miniProgressTrack: {
    width: '100%',
    justifyContent: 'center',
    position: 'relative',
  },
  miniProgressDot: {
    position: 'absolute',
    left: 0,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#2FA2FE',
    top: -4.5,
  },
  miniProgressLine: {
    width: '100%',
    height: 5,
    backgroundColor: '#D9D9D9',
  },
  bottomBarInner: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 8,
    paddingTop: 0,
    paddingBottom: 10,
    backgroundColor: '#FAFAFA',
    borderRadius: 14,
  },
  bottomItem: {
    alignItems: 'center',
  },
  bottomIconMuted: {
    width: 50,
    height: 50,
    marginTop: 0,
  },
  bottomMicButton: {
    width: 52,
    height: 52,
    borderRadius: 10,
    backgroundColor: '#42A5F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomMicIcon: {
    width: 30,
    height: 30,
  },
  recordStopSquare: {
    position: 'absolute',
    width: 15,
    height: 15,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
  },
  youtubeBadge: {
    width: 50,
    height: 35,
  },
  bottomLabel: {
    marginTop: 6,
    fontSize: 12,
    color: '#6A6A6F',
  },
  youtubeLabel: {
    marginBottom: 0,
  },
  bottomLabelMuted: {
    marginTop: 0,
    marginBottom: 0,
    fontSize: 12,
    color: '#8E8E93',
  },
});
