import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  historyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2FA2FE',
    height: 57,
    paddingLeft: 12,
    paddingRight: 14,
    marginHorizontal: 16,
    marginBottom: 8,
  },
  historyEditIcon: {
    width: 24,
    height: 24,
    marginRight: 11,
  },
  historyCardText: {
    flex: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    color: '#1F1F23',
  },
  historyDeleteBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 11,
  },
  trashIconWrap: {
    width: 20,
    height: 22,
    alignItems: 'center',
  },
  trashLid: {
    width: 18,
    height: 0,
    borderTopWidth: 1.5,
    borderTopColor: '#434343',
    marginTop: 3,
  },
  trashHandle: {
    position: 'absolute',
    top: 0,
    width: 8,
    height: 3,
    borderWidth: 1.5,
    borderBottomWidth: 0,
    borderColor: '#434343',
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },
  trashBody: {
    width: 14,
    height: 14,
    borderWidth: 1.5,
    borderTopWidth: 0,
    borderColor: '#434343',
    borderBottomLeftRadius: 3,
    borderBottomRightRadius: 3,
    marginTop: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingTop: 2,
  },
  trashLine: {
    width: 0,
    height: 8,
    borderLeftWidth: 1.5,
    borderLeftColor: '#434343',
  },
});
