import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  settingsOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000000',
    zIndex: 50,
  },
  settingsOverlayPress: {
    flex: 1,
  },
  settingsSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 30,
    zIndex: 60,
    maxHeight: '80%',
  },
  langRowWrap: {
    position: 'relative',
    marginBottom: 10,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#434343',
    borderRadius: 8,
  },
  settingsRowActiveLang: {
    borderColor: '#2FA2FE',
  },
  settingsRowText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#333333',
  },
  chevronArrow: {
    width: 10,
    height: 10,
    borderRightWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: '#434343',
    transform: [{rotate: '45deg'}],
    marginBottom: 4,
  },
  chevronArrowOpen: {
    borderColor: '#2FA2FE',
    transform: [{rotate: '-135deg'}],
    marginBottom: -2,
    marginTop: 4,
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    gap: 80,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  radioCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#48484859',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioCircleSelected: {
    backgroundColor: '#2079C0',
  },
  checkmark: {
    width: 10,
    height: 6,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderColor: '#FFFFFF',
    transform: [{rotate: '-45deg'}],
    marginTop: -1,
  },
  radioLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#333333',
  },
  settingsButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
    paddingBottom: 10,
  },
  cancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#E0F1FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2079C0',
  },
  saveBtn: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#2079C0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  langPanelFloat: {
    position: 'absolute',
    top: 74,
    left: 20,
    right: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#2FA2FE',
    borderRadius: 8,
    paddingBottom: 10,
    elevation: 5,
    zIndex: 20,
  },
  searchBarWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: '#43434352',
    borderRadius: 8,
    marginTop: 9,
    marginHorizontal: 4,
    paddingLeft: 10,
  },
  searchIconWrap: {
    width: 14,
    height: 14,
    marginRight: 6,
    position: 'relative',
  },
  searchIconCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: '#434343',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  searchIconHandle: {
    width: 5,
    height: 0,
    borderTopWidth: 1.5,
    borderTopColor: '#434343',
    position: 'absolute',
    bottom: 1.5,
    right: 0,
    transform: [{rotate: '45deg'}],
  },
  searchInput: {
    flex: 1,
    paddingVertical: 8,
    fontSize: 13,
    fontWeight: '400',
    color: '#333333',
  },
  langListWrap: {
    position: 'relative',
    maxHeight: 200,
  },
  langList: {
    maxHeight: 200,
    paddingRight: 14,
  },
  langScrollTrack: {
    position: 'absolute',
    top: 4,
    bottom: 4,
    right: 4,
    width: 5,
    backgroundColor: '#CFCFCF',
    borderRadius: 2.5,
  },
  langScrollThumb: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 5,
    height: 22,
    borderRadius: 2.5,
    backgroundColor: '#2FA2FE',
  },
  langOption: {
    paddingVertical: 4,
    paddingLeft: 11,
  },
  langOptionText: {
    fontSize: 13,
    color: '#333333',
    fontWeight: '400',
  },
  langOptionTextSelected: {
    color: '#2FA2FE',
    fontWeight: '600',
  },
});
